2014DI/di-test-20140420/ViewModels/BandEventVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace di_test_20140420.ViewModels
{
    public class BandEventVM
    {
        public string SearchText { get; set; }

        public string EventsAsJson { get; set; }

    }
}

2014DI/di-test-20140420/ViewModels/BandVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace di_test_20140420.ViewModels
{
    public class BandVM
    {

        public string SearchText { get; set; }

        public string BandsAsJson { get; set; }
    }
}

2014DI/di-test-20140420/Controllers/BandEventController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClientFacade.Interfaces;
using di_test_20140420.Parsers;
using di_test_20140420.ViewModelBuilders;
using di_test_20140420.ViewModels;

namespace di_test_20140420.Controllers
{
    public class BandEventController : Controller
    {
       
        private readonly IBandEventFacade _bandEventFacade;

        public BandEventController(IBandEventFacade injectedBandEventFacade)
        {
            _bandEventFacade = injectedBandEventFacade;
        }

        public ActionResult Index()
        {
            return View(new BandEventVM());
        }

        public ActionResult SearchForBands(BandEventVM model)
        {
            model =  SearchForEventsByBandName(model.SearchText);
            return View("Index", model);
        }


        private BandEventVM SearchForEventsByBandName(string searchText)
        {
            return BandEventVMBuilder.BuildModel(_bandEventFacade.GetEventsFromLastFm(searchText));
        }

        
    }
}

2014DI/di-test-20140420/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientFacade.Interfaces;
using di_test_20140420.ViewModelBuilders;
using di_test_20140420.ViewModels;

namespace di_test_20140420.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBandFacade _bandFacade;

        public HomeController(IBandFacade _injectedBandFacade)
        {
            _bandFacade = _injectedBandFacade;

        }
        
        public ActionResult Index()
        {
            BandVM model = BandVMBuilder.BuildModel(_bandFacade.GetBandsByPrefix("Wata"));
            return View(model);
        }
        
        [HttpPost]
        public ActionResult GetBandByPrefix(BandVM bandVm)
        {
            if (!string.IsNullOrEmpty(bandVm.SearchText))
            {
                bandVm = BandVMBuilder.BuildModel(_bandFacade.GetBandsByPrefix(bandVm.SearchText));
            }
            return View("Index", bandVm);
        }

        [HttpPost]
        public ActionResult GetBandByPrefixNoCheck(BandVM bandVm)
        {
           bandVm = BandVMBuilder.BuildModel(_bandFacade.GetBandsByPrefix(bandVm.SearchText));
           return View("Index", bandVm);
        }

    }
}

2014DI/di-test-20140420/Views/BandEvent/Index.cshtml
@model di_test_20140420.ViewModels.BandEventVM 

@{
    ViewBag.Title = "Search for events from band name";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/BandEvent.js"></script>
@Html.HiddenFor(X=> X.EventsAsJson)

<div>
    <table class="rwd-table" id="eventTable">
        <tr>
            <th>
                HeadLiner    
            </th>
            <th>
                City
            </th>
             <th>
                Date    
            </th>
            <th>
                Venue
            </th>
             <th>
                Other artists    
            </th>
            <th>
                Url
            </th>

        </tr>
    </table>
</div>



@using (Html.BeginForm("SearchForBands","BandEvent"))
{
    <label class="left">Search for band events</label>
    <div class="clear"></div>
    <div class="left">
        @Html.TextBoxFor(X=> X.SearchText)
    </div>
    <div class="left">
        <input type="submit" value="Search"/>
    </div>
    <div class="clear"></div>
}



<script type="text/javascript">
    InitHome();
</script>

2014DI/di-test-20140420/Views/Home/Index.cshtml
@model di_test_20140420.ViewModels.BandVM 

@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<script src="~/Scripts/Home.js"></script>
@Html.HiddenFor(X=> X.BandsAsJson)

<div>
    <table class="rwd-table"  id="bandTable">
        <tr>
            <th>
                BandName    
            </th>
            <th>
                Origin
            </th>
        </tr>
    </table>
</div>
<div>

@using (Html.BeginForm("GetBandByPrefix","Home"))
{
    <label class="left">Search for band</label>
    <div class="clear"></div>
    <div class="left">
        @Html.TextBoxFor(X=> X.SearchText)
    </div>
    <div class="left">
        <input type="submit" value="Search"/>
    </div>
    <div class="clear"></div>
}
</div>

<div class="left">
    <a href="@Url.Action("Index","BandEvent")">Go to band events page</a>
    <div class="clear"></div>
</div>

<script type="text/javascript">
    InitHome();
</script>

2014DI/di-test-20140420/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

</head>
<body>
    @RenderBody()

    
</body>
</html>